version: '2'

services:
    web:
        container_name: web
        image: php:7.2-apache-stretch
        ports:
            - "8080:80"
        volumes:
            - ~/docker/www:/var/www/html
        links:
            - db:db
    db:
        container_name: db
        image: mysql:5.7
        volumes:
            - ~/docker/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
    myadmin:
        container_name: myadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        links:
            - db:db
