version: '3'

services:
    web:
        container_name: web
# J'utilise une image que j'ai créée avec les extensions qui vont bien
# docker build -t php7.2-with-ext images/php/
        image: php7.2-with-ext
        ports:
            - "8080:80"
        volumes:
            - ~/VM/docker/www:/var/www/html
        links:
            - db:db
#        user: 1000:1000
#        environment:
#            - APACHE_RUN_USER=#1000
    db:
        container_name: db
        image: mysql:5.7
        volumes:
            - ~/VM/docker/data/mysql/xampp:/var/lib/mysql
            # Fichier de config spécifique pour mettre la base en debug (attention à la volumétrie de la table general_log)
            - ./config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
    myadmin:
        container_name: myadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        links:
            - db:db
