version: '3.1'

services:
  php:
    image: php5.6-with-ext
    ports:
      - 8080:80
    volumes:
      - ./public_html:/var/www/html/
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./php.ini-development:/usr/local/etc/php/php.ini
  db:
      container_name: db
      image: mysql:5.7
      volumes:
          - ./data/mysql:/var/lib/mysql
          # Fichier de config spécifique pour mettre la base en debug (attention à la volumétrie de la table general_log)
          #- ./config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      ports:
          - "3306:3306"
      environment:
          - MYSQL_ROOT_PASSWORD=root
  myadmin:
      container_name: myadmin
      image: phpmyadmin/phpmyadmin
      ports:
          - "8082:80"
      links:
          - db:db
